export const teams = [
    {
        id: 1,
        name: "India",
        board: "BCCI",
        region: "Asia",
        tournament: "International",
        format: "ODI",
        captain: "Rohit Sharma",
        captainImage: "https://i.pravatar.cc/150?img=11",
        rank: 1,
        points: 126,
        rankChange: 2,
        flag: "https://flagcdn.com/w320/in.png",
        borderColor: "#A3FF3D",
    },
    {
        id: 2,
        name: "Australia",
        board: "Cricket Australia",
        region: "Oceania",
        tournament: "International",
        format: "Test",
        captain: "Pat Cummins",
        captainImage: "https://i.pravatar.cc/150?img=12",
        rank: 2,
        points: 118,
        rankChange: 0,
        flag: "https://flagcdn.com/w320/au.png",
        borderColor: "#B5FFE0",
    },
    {
        id: 3,
        name: "England",
        board: "ECB",
        region: "Europe",
        tournament: "International",
        format: "ODI",
        captain: "Jos Buttler",
        captainImage: "https://i.pravatar.cc/150?img=13",
        rank: 3,
        points: 115,
        rankChange: -1,
        flag: "https://flagcdn.com/w320/gb.png",
        borderColor: "#FFB5B5",
    },
    {
        id: 4,
        name: "Pakistan",
        board: "PCB",
        region: "Asia",
        tournament: "International",
        format: "T20I",
        captain: "Babar Azam",
        captainImage: "https://i.pravatar.cc/150?img=14",
        rank: 4,
        points: 112,
        rankChange: 1,
        flag: "https://flagcdn.com/w320/pk.png",
        borderColor: "#A3FF3D",
    },
    {
        id: 5,
        name: "South Africa",
        board: "CSA",
        region: "Africa",
        tournament: "International",
        format: "Test",
        captain: "Temba Bavuma",
        captainImage: "https://i.pravatar.cc/150?img=15",
        rank: 5,
        points: 108,
        rankChange: -2,
        flag: "https://flagcdn.com/w320/za.png",
        borderColor: "#F7D774",
    },
    {
        id: 6,
        name: "New Zealand",
        board: "NZC",
        region: "Oceania",
        tournament: "International",
        format: "T20I",
        captain: "Mitchell Santner",
        captainImage: "https://i.pravatar.cc/150?img=16",
        rank: 6,
        points: 105,
        rankChange: 0,
        flag: "https://flagcdn.com/w320/nz.png",
        borderColor: "#8FD3FF",
    }
];