export const standings = [
    {
        pos: 1,
        team: "Mumbai Strikers",
        status: "Qualified",
        played: 14,
        won: 11,
        lost: 3,
        points: 22,
        nrr: "+1.450",
        recentForm: ["W", "W", "L", "W", "W"],
    },
    {
        pos: 2,
        team: "Delhi Titans",
        status: "Qualified",
        played: 14,
        won: 10,
        lost: 4,
        points: 20,
        nrr: "+0.890",
        recentForm: ["W", "W", "W", "L", "W"],
    },
    {
        pos: 3,
        team: "Gujrat Titans",
        status: "Unqualified",
        played: 14,
        won: 10,
        lost: 4,
        points: 20,
        nrr: "+0.890",
        recentForm: ["W", "W", "W", "L", "W"],
    },
];